FROM golang:1.26 AS builder
WORKDIR /src
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/vault-env-runner ./cmd/runner

FROM gcr.io/distroless/base-debian12
COPY --from=builder /out/vault-env-runner /usr/local/bin/vault-env-runner
ENTRYPOINT ["/usr/local/bin/vault-env-runner"]
