FROM golang:1.25 AS builder
WORKDIR /src
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/webhook ./cmd/webhook

FROM gcr.io/distroless/base-debian12
COPY --from=builder /out/webhook /usr/local/bin/webhook
EXPOSE 8443
ENTRYPOINT ["/usr/local/bin/webhook"]
